### ISSUE TITLE
escaping '-' :-\

### ISSUE THREAD

**Issue by askovpen** [aaronsw/html2text#101]
``` html
<p>- test</p>
```

why result?

```
\- test
```

**Comment by Alir3z4** [comment]
@askovpen otherwise it's a list.

**Comment by askovpen** [comment]
how to disable it?

**Comment by Alir3z4** [comment]
You can find the options here: https://github.com/Alir3z4/html2text/blob/master/docs/usage.md#command-line-options

This repo is not being maintained anymore (#91), new repo:  https://github.com/Alir3z4/html2text/
