### ISSUE TITLE
foo<br>bar inserts a blank line

### ISSUE THREAD

**Issue by benw** [aaronsw/html2text#12]
Input:

```
foo<br>bar
```

Current output:

```
foo

bar

```

Preferred output:

```
foo<sp><sp>
bar
```

i.e. append [two spaces](http://daringfireball.net/projects/markdown/syntax#p) to foo, to keep the same formatting as the `<br>`.

**Comment by aaronsw** [comment]
Seems to be caused by optwrap. textwrap.wrap tosses the trailing spaces and then optwrap breaks the line up into paragraphs.
