### ISSUE TITLE
Support for `text-decoration: line-through`

### ISSUE THREAD

**Issue by ceuk** [aaronsw/html2text#128]
Hi, would it be feasible to implement ~~strike-through~~ text conversion based on the `text-decoration` CSS prop? 

I could have a go this evening if you think it would be possible (haven't investigated yet) and would be open to a PR?

**Comment by KrishGarg** [comment]
umm you do know that he is dead?

**Comment by ceuk** [comment]
oh wow I didn't even see who made this :grimacing:
