### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aledr** [aaronsw/html2text#31]
html2text page at http://www.aaronsw.com/2002/html2text state license as GNU GPL 3.0 but there is no COPYING file into the sources.
Can you please add the GPL 3 COPYING file to avoid legal problems when packaging html2text?

Thanks.

**Comment by aaronsw** [comment]
Added.

**Comment by aledr** [comment]
Sorry, maybe I missed it.
Will it be present on the next releases tarball?

Thanks again.

**Comment by aaronsw** [comment]
I assume. I just run `python setup.py sdist upload` to upload the tarballs to PyPI, so if that includes it then it will be included.

**Comment by aledr** [comment]
I'm not seeing the file at Github, do you keep the sources at another place?

**Comment by aaronsw** [comment]
Huh, looks like I screwed up the history somehow. Should be there now.

**Comment by aledr** [comment]
Hi there...

COPYING file is not yet included in tarball releases.

Thanks.

**Comment by aaronsw** [comment]
The release instructions are described in `README.md`. If you know how to get the COPYING file included, let me know or file a pull request. I don't see how to do it.
