### ISSUE TITLE
xrange is not supported in Python3

### ISSUE THREAD

**Issue by fzakaria** [aaronsw/html2text#85]
This module gives the impression it supports Python 3 however xrange is unsupported in Python 3.

I suggest changing it to range or importing xrange from six module in Python 3 ! :)

**Comment by mcepl** [comment]
html2text in this repo is NOT Python3 compliant. There are many more issues with python3 compliance than just xrange. I have working python3 version in https://github.com/mcepl/html2text/tree/next and https://github.com/Alir3z4/html2text (what probably might be an interim replacement repo, see #91) has it as well.

I think this could be safely closed as NOTABUG.

**Comment by fzakaria** [comment]
CLosing as NOTABUG
