### ISSUE TITLE
The author has passed away

### ISSUE THREAD

**Issue by xiaoxu193** [aaronsw/html2text#86]
Just a heads up that this project is no longer being maintained because the author, Aaron Swartz, has passed way. New pull requests won't be merged.

http://en.wikipedia.org/wiki/Aaron_Swartz

http://nymag.com/news/features/aaron-swartz-2013-2/

**Comment by dontdieych** [comment]
RIP

## 

rss2email user

**Comment by daegun** [comment]
this should be stickied or something.

**Comment by mcepl** [comment]
> Just a heads up that this project is no longer being maintained because the author, Aaron Swartz, has passed way. New pull requests won't be merged.

Yes, which is the reason, why we try to revive with @Alir3z4 this project in https://github.com/html2text/html2text (later to be merged back, if the inheritance after Aaron will make this repo alive again).

**Comment by philfreo** [comment]
It seems the pip version ( https://pypi.python.org/pypi/html2text ) is being updated and maintained here:

https://github.com/Alir3z4/html2text/
