### ISSUE TITLE
UnicodeDecode Error

### ISSUE THREAD

**Issue by amritkrs** [aaronsw/html2text#96]
r = requests.get('http://en.wikipedia.org/wiki/Monty_Python')
 print html2text.html2text(r.content)
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "html2text.py", line 812, in html2text 
            return h.handle(html) 
File "html2text.py", line 254, in handle 
          return self.optwrap(self.close()) 
File "html2text.py", line 266, in close 
self.outtext = self.outtext.join(self.outtextlist)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)

**Comment by mcepl** [comment]
```
matej@mitmanek: ~$ html2text http://en.wikipedia.org/wiki/Monty_Python>/dev/null ; echo $?
0
matej@mitmanek: ~$
```

Get the updated code from https://github.com/Alir3z4/html2text or from my repository http://luther.ceplovi.cz/git/html2text.git. This repository is literally dead, because its author is.

**Comment by amritkrs** [comment]
@mcepl Thanks bro.

**Comment by amritkrs** [comment]
@mcepl  inspite of using html2text from https://github.com/Alir3z4/html2text i still face the same problem.
r = requests.get("http://en.wikipedia.org/wiki/Python_%28programming_language%29")
print html2text.html2text(r.content)

Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "html2text/**init**.py", line 750, in html2text
return h.handle(html) 
File "html2text/**init**.py", line 121, in handle 
return self.optwrap(self.close())
File "html2text/**init**.py", line 139, in close 
outtext = nochr.join(self.outtextlist)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 62: ordinal not in range(128)

**Comment by mcepl** [comment]
File a bug to @Alir3z4 then.

**Comment by amritkrs** [comment]
OK
